### ISSUE TITLE
[ModernSearch] Upgrade to SPFx v1.8.2

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-solutions#99]
I'm planning to start the upgrade of the Modern Search to v1.8.1 of SPFx. Current plan are the following steps, if there are concerns/other approaches etc. let me know before I start ;)
@FranckyC @wobba 

#### Todo
- [x] Upgrade to SPFX v1.8.2
- [x] Upgrade to TypeScript v3.3
- [ ] ~Upgrade Office UI Fabric React~

**Comment by wobba** [comment]
Question is why? Upgrade at some point sure, but what benefits will 1.8 be now? You cannot really go ouifr 6 due to pnp reusable controls still on 5, to limit bundle size for one.

**Comment by YannickRe** [comment]
Wasn't aware of that. Benefits: probably none, just to keep up to date with the releases.
Good thing I asked first this time ;)

**Comment by YannickRe** [comment]
Only thing I can think of right now: better/stricter type checking with TypeScript 3.3 but no idea if that would clash with our other dependencies.

**Comment by wobba** [comment]
@YannickRe you could give it a go, just make sure runtime bundles stay the same. Edit mode is not so important.

**Comment by YannickRe** [comment]
@wobba I'm stubborn, so I started ;) but it wasn't so straightforward. Current issue is that the "office-ui-fabric" package got removed from SPFx 1.8, which breaks these lines:
https://github.com/SharePoint/sp-dev-solutions/blob/46898e61e6e82d87c3010bf305ded18140970e4e/solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/components/Layouts/SearchResultsTemplate.scss#L3-L6

Removing the lines results in very broken UI:
![BrokenUI](https://user-images.githubusercontent.com/9973962/55107987-e19c9380-50d2-11e9-8d3e-c2f9dba704d3.PNG)

Easiest workaround would be to install the package ourselves, but it kinda defeats the purpose as the core team decided to remove this package. Shelving this until I have time to understand why we loaded this and if I can make it work without returning to depend on this legacy package.

**Comment by wobba** [comment]
Ouif css is quirky. If you manage to make the default templates look good, that's what matters. They're not that great today and should resemble the highlighted wp imo. The other option is to cheat and implement those as custom renderers and not handlebars ;) Have fun and a good planning exercise regardless as we will upgrade at some point. Are we looking at v3 for this?

**Comment by YannickRe** [comment]
As a built-in (custom) renderer with Ouif React? Or as a separate package?

There is no timeline yet. A lot of things to do, not enough hours in a day and too much variables to commit to a timeline now.
I opened the ticket to get some feedback and decide on an approach when I encounter issues.

**Comment by wobba** [comment]
Separate ext in the same bundle. And love your energy on this 😀

**Comment by FranckyC** [comment]
> If you manage to make the default templates look good, that's what matters. 

@wobba @YannickRe I agree. Custom renderer is no the priority for now I think, we should improve the default handlebars template first because it's the main benefit of this WP in my opinion.

If someone has designer skills, go ahead to revamp this, even without ouif ;)

**Comment by YannickRe** [comment]
> Separate ext in the same bundle. And love your energy on this 😀

It turns out that investing some time in open source is my only option to still do actual coding, with a finished result. In my day job, I tend to only do POC's and talks so this gives me some energy 😊

> > If you manage to make the default templates look good, that's what matters.
> 
> @wobba @YannickRe I agree. Custom renderer is no the priority for now I think, we should improve the default handlebars template first because it's the main benefit of this WP in my opinion.
> 
> If someone has designer skills, go ahead to revamp this, even without ouif ;)
I don't like the handlebars, I'm in it for the custom renderers 😊 but agreed that it's a benefit for some to easily adjust the rendering.

**Comment by YannickRe** [comment]
Current status: running smooth, like with 1.7 but pretty sure we don't want to merge.

Overview of my approach:
### TypeScript
**Issue**: TypeScript does stricter checking now
![TypeScriptIssues](https://user-images.githubusercontent.com/9973962/55140171-bc8e3c00-5137-11e9-8332-161b566430fe.PNG)

**Resolution**: ootb 1.8 project adds some additional lines to tsconfig.json to surpress this, so I did too. Might be worth to turn off and improve the code, somewhere in the future.
```
"inlineSources": false,
"strictNullChecks": false,
"noUnusedLocals": false,
```
### Office UI Fabric React 6
**Issue**: 1.8 supports Ouifr 6, but @pnp/spfx-controls-react doesn't yet

**Resolution**: none, this is a hard dependency so I kept referencing Ouifr 5.
[Elio Struyf mentions other issues with v1.8](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/256#issuecomment-474031386) that the SP Engineering Team has to fix first before he can even consider upgrading @pnp/spfx-controls-react
 
### Office UI Fabric styling (part 1)
**Issue**: Our built-in Handlebars templates import Office UI Fabric styling, but this package is not included by default anymore in v1.8.

**Resolution**: some options discusses above, to be able to continue working I took it as a dependency in our project for now.

### Office UI Fabric styling (part 2)
**Issue**: the controls we use and the styling we created, expect the Office UI Fabric styling to be loaded but with v1.8 they aren't anymore.

**Resolution**: add the following code to the manifest file of each web part:
```
"loadLegacyFabricCss": true,
```

**Resolution issue**: although described as a supported approach in the v1.8 release notes,[ this does not work as expected](https://github.com/SharePoint/sp-dev-docs/issues/3612). Using the workaround mentioned there, it works, but don't think we can release a solution where you have to manually adjust a file somewhere in your node_modules folder.

So, a fun evening activity providing more insights, but seems we best stick to v1.7.1 for a while 😊

**Comment by wobba** [comment]
Appreciate the feedback on this - and good info for when we do migrate.

**Comment by YannickRe** [comment]
I went ahead and tried the upgrade with v1.8.1 since it should fix the loadLegacyFabricCss bug. Currently hitting a new issue with regards to dynamic data in the hosted workbench only, find more info at https://github.com/SharePoint/sp-dev-docs/issues/3820

**Comment by bartvermeersch** [comment]
Not yet supporting spfx v1.8 also results in not being able to build using NodeJS LTS version 10? According to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment NodeJS LTS version 10 can now be used. Or is this caused by something issue? Thanks!

**Comment by YannickRe** [comment]
@bartvermeersch Node v10 is supported from version 1.8.2 of SPFx. Since this solution isn't upgraded yet, it requires 1.7.1 and thus doesn't support Node v10.
Upgrade to 1.8.0 and 1.8.1 was blocked due to bugs in SPFx, I have planned to retry the upgrade soon (with 1.8.2). All previous blocking issues aare supposed to be fixed, if no new come up I'll get a PR ready.
